"""add minimum_roster to seasons

Revision ID: 03a695e6b247
Revises: 5f808661e8a9
Create Date: 2026-08-18 17:59:23.529055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a695e6b247'
down_revision: Union[str, Sequence[str], None] = '5f808661e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows; dropped afterward since new
    # inserts always supply it via the Python-side default in models.py.
    op.add_column(
        "seasons",
        sa.Column("minimum_roster", sa.Integer(), nullable=False, server_default="12"),
    )
    op.alter_column("seasons", "minimum_roster", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'minimum_roster')
    # ### end Alembic commands ###
