"""add substitute pairing, gender, absence cancellation, and change deadline

Revision ID: 059333b297ff
Revises: b5ed36392784
Create Date: 2026-09-05 04:17:04.370532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059333b297ff'
down_revision: Union[str, Sequence[str], None] = 'b5ed36392784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absences', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('drop_ins', sa.Column('covers_absence_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drop_ins', 'absences', ['covers_absence_id'], ['id'])
    op.add_column('players', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('change_deadline_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'change_deadline_days')
    op.drop_column('players', 'gender')
    op.drop_constraint(None, 'drop_ins', type_='foreignkey')
    op.drop_column('drop_ins', 'covers_absence_id')
    op.drop_column('absences', 'cancelled_at')
    # ### end Alembic commands ###
