"""add membership intent to club members

Revision ID: 17a1f846cb57
Revises: 6295ae10259f
Create Date: 2026-09-08 03:42:56.830786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a1f846cb57'
down_revision: Union[str, Sequence[str], None] = '6295ae10259f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_members', sa.Column('wants_fixed_membership', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_members', 'wants_fixed_membership')
    # ### end Alembic commands ###
