"""record who brought a drop-in

Revision ID: 4560ad02d5d6
Revises: dda56e5e25a2
Create Date: 2026-09-09 04:47:37.420087

Additive and nullable, so it applies to a live database without
touching a single existing row: every drop-in recorded before now keeps
a null, which reads correctly as "signed themselves up, or we don't
know". Nothing in billing depends on it — see DropInRow.brought_by_player_id.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4560ad02d5d6"
down_revision: str | Sequence[str] | None = "dda56e5e25a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Named rather than left to the autogenerated None: `drop_constraint(None,
# ...)` raises on downgrade, so an unnamed constraint makes this
# migration one-way without saying so.
_FK = "fk_drop_ins_brought_by_player_id_players"


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "drop_ins", sa.Column("brought_by_player_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(_FK, "drop_ins", "players", ["brought_by_player_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(_FK, "drop_ins", type_="foreignkey")
    op.drop_column("drop_ins", "brought_by_player_id")
