"""add uniqueness, check constraints, and foreign key indexes

Revision ID: 5f3c4c0c93ba
Revises: 059333b297ff
Create Date: 2026-09-06 05:55:42.496733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3c4c0c93ba'
down_revision: Union[str, Sequence[str], None] = '059333b297ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check constraints aren't picked up by autogenerate — added by hand.
    op.create_check_constraint(
        'ck_players_gender', 'players', "gender IN ('male', 'female')"
    )
    op.create_check_constraint(
        'ck_seasons_venue_cost_non_negative', 'seasons', 'total_venue_cost >= 0'
    )
    op.create_check_constraint(
        'ck_seasons_capacity_positive', 'seasons', 'capacity > 0'
    )
    op.create_check_constraint(
        'ck_seasons_minimum_roster_non_negative', 'seasons', 'minimum_roster >= 0'
    )
    op.create_check_constraint(
        'ck_seasons_change_deadline_non_negative',
        'seasons',
        'change_deadline_days >= 0',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_absences_game_id', 'absences', ['game_id'], unique=False)
    op.create_index('uq_absences_active_player_game', 'absences', ['player_id', 'game_id'], unique=True, postgresql_where=sa.text('cancelled_at IS NULL'), sqlite_where=sa.text('cancelled_at IS NULL'))
    op.create_index('ix_drop_ins_covers_absence_id', 'drop_ins', ['covers_absence_id'], unique=False)
    op.create_index('ix_drop_ins_game_id', 'drop_ins', ['game_id'], unique=False)
    op.create_index('uq_drop_ins_active_player_game', 'drop_ins', ['player_id', 'game_id'], unique=True, postgresql_where=sa.text('cancelled_at IS NULL'), sqlite_where=sa.text('cancelled_at IS NULL'))
    op.create_index('ix_games_season_id', 'games', ['season_id'], unique=False)
    op.create_index('ix_ledger_entries_player_id', 'ledger_entries', ['player_id'], unique=False)
    op.create_index('ix_ledger_entries_season_id', 'ledger_entries', ['season_id'], unique=False)
    op.create_unique_constraint('uq_players_name', 'players', ['name'])
    op.create_index('ix_season_members_player_id', 'season_members', ['player_id'], unique=False)
    op.create_index('ix_waitlist_entries_game_id', 'waitlist_entries', ['game_id'], unique=False)
    op.create_unique_constraint('uq_waitlist_player_game', 'waitlist_entries', ['player_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_waitlist_player_game', 'waitlist_entries', type_='unique')
    op.drop_index('ix_waitlist_entries_game_id', table_name='waitlist_entries')
    op.drop_index('ix_season_members_player_id', table_name='season_members')
    op.drop_constraint('uq_players_name', 'players', type_='unique')
    op.drop_index('ix_ledger_entries_season_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_player_id', table_name='ledger_entries')
    op.drop_index('ix_games_season_id', table_name='games')
    op.drop_index('uq_drop_ins_active_player_game', table_name='drop_ins', postgresql_where=sa.text('cancelled_at IS NULL'), sqlite_where=sa.text('cancelled_at IS NULL'))
    op.drop_index('ix_drop_ins_game_id', table_name='drop_ins')
    op.drop_index('ix_drop_ins_covers_absence_id', table_name='drop_ins')
    op.drop_index('uq_absences_active_player_game', table_name='absences', postgresql_where=sa.text('cancelled_at IS NULL'), sqlite_where=sa.text('cancelled_at IS NULL'))
    op.drop_index('ix_absences_game_id', table_name='absences')
    # ### end Alembic commands ###

    op.drop_constraint('ck_seasons_change_deadline_non_negative', 'seasons', type_='check')
    op.drop_constraint('ck_seasons_minimum_roster_non_negative', 'seasons', type_='check')
    op.drop_constraint('ck_seasons_capacity_positive', 'seasons', type_='check')
    op.drop_constraint('ck_seasons_venue_cost_non_negative', 'seasons', type_='check')
    op.drop_constraint('ck_players_gender', 'players', type_='check')
