"""add capacity to seasons

Revision ID: 5f808661e8a9
Revises: f657d4a32fb1
Create Date: 2026-08-17 22:03:57.628685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f808661e8a9'
down_revision: Union[str, Sequence[str], None] = 'f657d4a32fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (there's already test data in
    # Neon with no capacity value); dropped afterward since new inserts
    # always supply it via the Python-side default in models.py.
    op.add_column(
        "seasons",
        sa.Column("capacity", sa.Integer(), nullable=False, server_default="18"),
    )
    op.alter_column("seasons", "capacity", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'capacity')
    # ### end Alembic commands ###
