"""add clubs and club_members, make Club the tenant boundary

Revision ID: 6295ae10259f
Revises: da02e3f499c3
Create Date: 2026-09-06 23:53:44.696029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6295ae10259f'
down_revision: Union[str, Sequence[str], None] = 'da02e3f499c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_members',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('organizer', 'member')", name='ck_club_members_role'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('club_id', 'player_id')
    )
    op.create_index('ix_club_members_player_id', 'club_members', ['player_id'], unique=False)
    op.add_column('ledger_entries', sa.Column('club_id', sa.Integer(), nullable=False))
    op.create_index('ix_ledger_entries_club_id', 'ledger_entries', ['club_id'], unique=False)
    op.create_foreign_key(None, 'ledger_entries', 'clubs', ['club_id'], ['id'])
    op.drop_constraint(op.f('uq_players_name'), 'players', type_='unique')
    op.add_column('seasons', sa.Column('club_id', sa.Integer(), nullable=False))
    op.create_index('ix_seasons_club_id', 'seasons', ['club_id'], unique=False)
    op.create_foreign_key(None, 'seasons', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seasons', type_='foreignkey')
    op.drop_index('ix_seasons_club_id', table_name='seasons')
    op.drop_column('seasons', 'club_id')
    op.create_unique_constraint(op.f('uq_players_name'), 'players', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_index('ix_ledger_entries_club_id', table_name='ledger_entries')
    op.drop_column('ledger_entries', 'club_id')
    op.drop_index('ix_club_members_player_id', table_name='club_members')
    op.drop_table('club_members')
    op.drop_table('clubs')
    # ### end Alembic commands ###
