"""add game time slot to seasons

Revision ID: a019526be0e5
Revises: a96614a76df9
Create Date: 2026-09-04 04:14:21.963388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a019526be0e5'
down_revision: Union[str, Sequence[str], None] = 'a96614a76df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('game_start_time', sa.Time(), nullable=True))
    op.add_column('seasons', sa.Column('game_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'game_end_time')
    op.drop_column('seasons', 'game_start_time')
    # ### end Alembic commands ###
