"""add ledger tracking fields

Revision ID: a96614a76df9
Revises: 03a695e6b247
Create Date: 2026-09-02 14:20:31.594624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96614a76df9'
down_revision: Union[str, Sequence[str], None] = '03a695e6b247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('ledger_entries', sa.Column('note', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ledger_entries', 'seasons', ['season_id'], ['id'])
    op.add_column('seasons', sa.Column('settled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'settled_at')
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'note')
    op.drop_column('ledger_entries', 'season_id')
    # ### end Alembic commands ###
