"""add line_user_id and avatar_url to players

Revision ID: da02e3f499c3
Revises: 5f3c4c0c93ba
Create Date: 2026-09-06 22:18:39.600101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da02e3f499c3'
down_revision: Union[str, Sequence[str], None] = '5f3c4c0c93ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('line_user_id', sa.String(), nullable=True))
    op.add_column('players', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_unique_constraint('uq_players_line_user_id', 'players', ['line_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_players_line_user_id', 'players', type_='unique')
    op.drop_column('players', 'avatar_url')
    op.drop_column('players', 'line_user_id')
    # ### end Alembic commands ###
