"""add problem report screenshots

Revision ID: dda56e5e25a2
Revises: de075457ba0e
Create Date: 2026-09-08 05:01:09.059175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda56e5e25a2'
down_revision: Union[str, Sequence[str], None] = 'de075457ba0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_reports')
    # ### end Alembic commands ###
