"""add client token to ledger entries

Revision ID: de075457ba0e
Revises: 17a1f846cb57
Create Date: 2026-09-08 04:36:10.243286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de075457ba0e'
down_revision: Union[str, Sequence[str], None] = '17a1f846cb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('client_token', sa.String(), nullable=True))
    op.create_index('uq_ledger_entries_client_token', 'ledger_entries', ['client_token'], unique=True, postgresql_where=sa.text('client_token IS NOT NULL'), sqlite_where=sa.text('client_token IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_entries_client_token', table_name='ledger_entries', postgresql_where=sa.text('client_token IS NOT NULL'), sqlite_where=sa.text('client_token IS NOT NULL'))
    op.drop_column('ledger_entries', 'client_token')
    # ### end Alembic commands ###
